### PR TITLE
Publishing to Maven repository

### PR DESCRIPTION
**Pull request by piotrrzysko**

### CODE REVIEW

**Comment by piotrrzysko** [comment]
Hello @lemire,

I'd like to publish the first release to the Maven repository, but there are two preliminary steps for which I lack the necessary permissions:

1. I wanted to register the `org.simdjson` groupId in Nexus: https://issues.sonatype.org/browse/OSSRH-94710. However, according to this comment: https://issues.sonatype.org/browse/OSSRH-94710?focusedId=1287512&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-1287512, before registering the groupId, it's necessary to add a DNS TXT record with the text `OSSRH-94710` to the `simdjson.org` domain. If I'm not mistaken, `simdjson.org` is registered through NameCheap, so the steps described in this documentation: https://www.namecheap.com/support/knowledgebase/article.aspx/317/2237/how-do-i-add-txtspfdkimdmarc-records-for-my-domain/ should suffice to add the record. Could you please add it?

2. Once I receive credentials for the Nexus repository, I'll need to add them to GitHub secrets (along with the PGP key). Unfortunately, I currently lack the necessary permissions to do so. If you don't mind, please consider assigning me the admin role in this project.

I'd be grateful if you could help me with these two points.

Thank you

**Comment by lemire** [comment]
You should already have admin access. Let me check.

**Comment by lemire** [comment]
Ok. Correct. You were not admin. It should have been corrected now, sorry about that, I always meant to give you admin access.

**Comment by lemire** [comment]
Capture d’écran, le 2023-09-04 à 15 08 43

The DNS record has been updated.

**Comment by piotrrzysko** [comment]
Thank you.

**Pull request merged**
